name: Update and test
env:
  COMMIT_MESSAGE: Continuous Integration compilation
  COMMIT_AUTHOR: Continuous Integration
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Use gringo and typescript
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gringo typescript
    - name: Test and Compile
      run: |
        npm ci
        npm run build --if-present
        npm test

        git config --global user.name "${{ env.COMMIT_AUTHOR }}"
        git config --global user.email "MatteoPuccio@users.noreply.github.com"
        git add out
        git commit -m "${{ env.COMMIT_MESSAGE }}"
        git push